version: '3'
services:
  main:
    build:
        context: .
        args:
            - http_proxy
            - https_proxy
            - no_proxy
    image: cubeearth/java-build-tooling
    ports:
    - 8080:8080
    - 5000:5000
    volumes:
    - ./nexus-data:/nexus-data:rw
